### ISSUE TITLE
Добавить новые каналы (Потоки ниже)

### ISSUE THREAD

**Issue by TaurerMedia** [anthonyaxenov/iptv#2]
Добавление новых потоков в плейлист:

Groovezzo: https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/7.m3u8
Криминал и Полиция: https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/5.m3u8
NINJA: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/3.m3u8
RRTV Europe: https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/6.m3u8
World-1: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/7.m3u8
KidsPlanet: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/4.m3u8
KidsPlanet+: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/2.m3u8
Quality HD: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/6.m3u8
Кулинар HD: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/14.m3u8
Sunset Movie: https://stream.sunset-media.ru:443/Free/Free/1.m3u8
Sunset Space: https://stream.sunset-media.ru:443/Free/Free/3.m3u8
Sunset Music: https://stream.sunset-media.ru:443/Free/Free/2.m3u8
Sunset Kids: https://stream.sunset-media.ru:443/Free/Free/4.m3u8

**Comment by anthonyaxenov** [comment]
@TaurerMedia добавить каналы в плейлисты не получится. Можно добавить ссылку на [ваш](https://github.com/TaurerMedia/TaurerPlus/blob/main/index.m3u8)

**Comment by TaurerMedia** [comment]
> @TaurerMedia добавить каналы в плейлисты не получится. Можно добавить ссылку на [ваш](https://github.com/TaurerMedia/TaurerPlus/blob/main/index.m3u8)

Давайте так, было бы круто.

**Comment by anthonyaxenov** [comment]
Добавлено с кодом `tp`
